name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write  # Required for OIDC
      issues: write # for semantic-release
      pull-requests: write # for semantic-release
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0
        with:
          cache: true
      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          package-manager-cache: false
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"
      - name: Build
        run: |
          pnpm install --frozen-lockfile
          pnpm test --run
          pnpm exec semantic-release
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ env.NODE_AUTH_TOKEN }}
