name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write  # Required for OIDC
      issues: write # for semantic-release
      pull-requests: write # for semantic-release
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          cache: true
      - name: Set up Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          package-manager-cache: false
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"
      - name: Build
        run: |
          pnpm install --frozen-lockfile
          pnpm test --run
          pnpm exec semantic-release
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ env.NODE_AUTH_TOKEN }}
